DROP SEQUENCE SEQUTILISATEUR;
/
DROP SEQUENCE SEQDOCUMENT;
/
DROP SEQUENCE DOCUMENT;
/
DROP TABLE DOCUMENT;
/
DROP TABLE UTILISATEUR;
/

CREATE SEQUENCE SEQUTILISATEUR
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE SEQUENCE SEQDOCUMENT
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 20;


CREATE TABLE DOCUMENT 
(
	IdDocument INTEGER PRIMARY KEY,
	IsReserver INTEGER NOT NULL,
	IsDisponible INTEGER NOT NULL
)
/

CREATE TABLE UTILISATEUR 
(
	IdUtilisateur INTEGER PRIMARY KEY,
	NomUtilisateur VARCHAR(30) NOT NULL,
	MotDePasse VARCHAR(30) NOT NULL,
	Login VARCHAR(30) NOT NULL,
	TypeUtilisateur VARCHAR(30) NOT NULL
)
/

INSERT INTO DOCUMENT (IdDocument,isReserver, isDisponible) VALUES (SEQDOCUMENT.NEXTVAL,0,1);
INSERT INTO DOCUMENT (IdDocument,isReserver, isDisponible) VALUES (SEQDOCUMENT.NEXTVAL,0,1);
INSERT INTO DOCUMENT (IdDocument,isReserver, isDisponible) VALUES (SEQDOCUMENT.NEXTVAL,0,1);

INSERT INTO UTILISATEUR (IdUtilisateur,NomUtilisateur, MotDePasse,Login, TypeUtilisateur) VALUES (SEQUTILISATEUR.NEXTVAL,'vadim','vadoom','vadime','Abonne');